spring.application.name=StudentCRUD_API_JPA

spring.datasource.url = jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=Khanna@1509

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
