server.port=8080

spring.application.name=DocAuthentication
spring.datasource.url=jdbc:mysql://localhost:3306/DocAppointment
spring.datasource.username=root
spring.datasource.password=Khanna@1509

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=SushilKhannaClinicAppSuperSecretKey2024XYZ