spring.application.name=E-commerce
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy
spring.datasource.username=root
spring.datasource.password=Khanna@1509

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

